source 'http://rubygems.org'

gem 'json'
# gem 'rest-client', '1.6.7'
gem 'sinatra', '1.4.5'
gem 'sinatra-activerecord'
gem 'sinatra-contrib'
gem 'activerecord'
gem 'rubyzip'

group :development do
  gem 'rerun'
  gem 'thin', '1.6.2'
  gem 'sqlite3'
  gem 'annotate', '>=2.6.0'
end
