
require 'sinatra'
require 'sinatra/activerecord'
require 'sinatra/activerecord/rake'

require_relative 'lib/mtg_tracker'

# Set correct database configuration
ActiveRecord::Tasks::DatabaseTasks.database_configuration = YAML.load_file("config/database.yml")

# Annotate gem task
namespace :annotate do
  desc "Annotate your models"
  task :models do |t, args|
    exec "annotate  --model-dir lib/mtg_tracker/models --position after"
  end
end

namespace :app do
  desc "Run backend"
  task :run, [:env] do |t, args|
    env = args[:env] || 'development'

    puts "Running in #{env} mode"
    exec "rerun --clear --dir lib -- rackup -E #{env} -p 4567"
  end
end
